'use client'
import { useEffect, useState, useCallback, useRef } from 'react'
import { Search as SearchIcon } from 'lucide-react'

interface PagefindModule {
  init: () => Promise<void>
  search: (q: string) => Promise<{
    results: Array<{ data: () => Promise<{ url: string; excerpt: string; meta: { title: string } }> }>
  }>
}

interface SearchResult {
  url: string
  title: string
  excerpt: string
}

export default function Search() {
  const [open, setOpen] = useState(false)
  const [query, setQuery] = useState('')
  const [results, setResults] = useState<SearchResult[]>([])
  const [unavailable, setUnavailable] = useState(false)
  const inputRef = useRef<HTMLInputElement>(null)
  const modalRef = useRef<HTMLDivElement>(null)
  const pagefindRef = useRef<PagefindModule | null>(null)

  // Keyboard shortcut
  useEffect(() => {
    const handler = (e: KeyboardEvent) => {
      if ((e.metaKey || e.ctrlKey) && e.key === 'k') {
        e.preventDefault()
        setOpen(o => !o)
      }
      if (e.key === 'Escape') setOpen(false)
    }
    window.addEventListener('keydown', handler)
    return () => window.removeEventListener('keydown', handler)
  }, [])

  // Focus input on open, reset on close
  useEffect(() => {
    if (open) setTimeout(() => inputRef.current?.focus(), 50)
    else { setQuery(''); setResults([]) }
  }, [open])

  // Load pagefind once on first open via dynamic import (works for ES modules)
  useEffect(() => {
    if (!open || pagefindRef.current) return
    // eslint-disable-next-line @typescript-eslint/ban-ts-comment
    // @ts-ignore — runtime-only file generated by pagefind build
    import(/* webpackIgnore: true */ '/pagefind/pagefind.js')
      .then(async (pf) => {
        const mod = pf as PagefindModule
        await mod.init()
        pagefindRef.current = mod
      })
      .catch(() => setUnavailable(true))
  }, [open])

  const runSearch = useCallback(async (q: string) => {
    if (!q.trim() || !pagefindRef.current) { setResults([]); return }
    try {
      const res = await pagefindRef.current.search(q)
      const data = await Promise.all(res.results.slice(0, 8).map(r => r.data()))
      setResults(data.map(d => ({ url: d.url.replace(/\.html$/, ''), title: d.meta.title, excerpt: d.excerpt })))
    } catch {
      setResults([])
    }
  }, [])

  useEffect(() => { runSearch(query) }, [query, runSearch])

  return (
    <>
      <button
        onClick={() => setOpen(true)}
        className="hidden md:flex items-center gap-2 px-3 py-1.5 rounded-lg border border-border text-text-muted text-sm hover:border-accent transition-colors"
      >
        <SearchIcon size={13} />
        <span>Search</span>
        <kbd className="ml-1 text-xs bg-surface px-1.5 py-0.5 rounded border border-border">⌘K</kbd>
      </button>

      {open && (
        <div
          className="fixed inset-0 z-50 flex items-start justify-center pt-24 bg-background/80 backdrop-blur-sm"
          onClick={() => setOpen(false)}
        >
          <div
            role="dialog"
            aria-modal="true"
            aria-label="Search"
            ref={modalRef}
            className="w-full max-w-xl bg-surface border border-border rounded-xl shadow-2xl overflow-hidden mx-4"
            onClick={e => e.stopPropagation()}
            onKeyDown={e => {
              if (e.key !== 'Tab' || !modalRef.current) return
              const focusable = modalRef.current.querySelectorAll<HTMLElement>(
                'a[href], button, input, [tabindex]:not([tabindex="-1"])'
              )
              const first = focusable[0]
              const last = focusable[focusable.length - 1]
              if (e.shiftKey ? document.activeElement === first : document.activeElement === last) {
                e.preventDefault()
                ;(e.shiftKey ? last : first).focus()
              }
            }}
          >
            <div className="flex items-center gap-3 px-4 py-3 border-b border-border">
              <SearchIcon size={16} className="text-text-muted flex-shrink-0" />
              <input
                ref={inputRef}
                value={query}
                onChange={e => setQuery(e.target.value)}
                placeholder="Search documentation..."
                className="flex-1 bg-transparent text-text-primary placeholder-text-muted outline-none text-sm"
              />
              <kbd className="text-xs text-text-muted bg-background px-1.5 py-0.5 rounded border border-border">
                Esc
              </kbd>
            </div>

            {unavailable && (
              <p className="px-4 py-6 text-sm text-text-muted text-center">
                Search index not found. Run <code className="font-mono text-accent">npm run build</code> to generate it.
              </p>
            )}

            {results.length > 0 && (
              <ul aria-live="polite" className="divide-y divide-border max-h-80 overflow-y-auto">
                {results.map(r => (
                  <li key={r.url}>
                    <a
                      href={r.url}
                      className="block px-4 py-3 hover:bg-background transition-colors"
                      onClick={() => setOpen(false)}
                    >
                      <p className="text-sm font-medium text-text-primary">{r.title}</p>
                      <p
                        className="text-xs text-text-muted mt-0.5 line-clamp-2"
                        dangerouslySetInnerHTML={{ __html: r.excerpt }}
                      />
                    </a>
                  </li>
                ))}
              </ul>
            )}

            {!unavailable && query && results.length === 0 && (
              <p className="px-4 py-6 text-sm text-text-muted text-center">
                No results for &quot;{query}&quot;
              </p>
            )}
          </div>
        </div>
      )}
    </>
  )
}
